distribution: xenial
language: node_js
node_js:
  - "10"
services:
  - docker
addons:
  apt:
    packages:
    - jq
before_script:
  - pip install --user yq
  - export ANTORA_COMPONENT_NAME="$(yq -r .name antora.yml)"
  - export ANTORA_COMPONENT_VERSION="$(yq -r .version antora.yml)"
  - export COMPONENT_NAME=$(yq -r '.name|.[3:]|sub("-";"_";"g")' antora.yml)
  - export COMPONENT_LANGUAGE=$(yq -r '.name|.[0:2]' antora.yml)
  - cd preview
  - npm install
  - export SUFFIX=".git"
  - export REPOSITORY_URL=$TRAVIS_REPO_SLUG$SUFFIX
  - echo $REPOSITORY_URL
  - gulp playbook
  - docker build -t wp .
script:
  - node_modules/.bin/antora --stacktrace --fetch --html-url-extension-style=indexify site.patched.yml
  - export HTML_FILE="$ANTORA_COMPONENT_NAME/$ANTORA_COMPONENT_VERSION/PDF/index.html"
  - export PDF_FILE="/build/doc.pdf"
  - export DOCKER_COMMAND="weasyprint -p $HTML_FILE $PDF_FILE"
  - echo $DOCKER_COMMAND
  - docker run --mount type=bind,source="$(pwd)"/build,target=/build --workdir /build wp $DOCKER_COMMAND
  - ls -l build
before_deploy:
  - export TRAVIS_TAG=latest
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - build/doc.pdf
  skip_cleanup: true
  on:
    repo: $TRAVIS_REPO_SLUG
  overwrite: true
env:
  global:
    - secure: E4z12+qWaJGrxbjnOVnNrTfkUc6vkFAzuLHaGOXYwVDaF11dNXxzAXyiYmad6rMi6MTuAzsVeKMFUt/VIJ0uGk5zwt3Oies0sZmrYZNNk0VYvg7iIvfJKuA0oclHeia70t0j9Ad/EuZj5omjAtQS3yJ+KVZrohNxTb33Ljo3hS3B03dfO87zHgfcoXSKDH/VNgxUjko1P/IGd5aXopSPEoPtrB+F8IoAm2HJGQ87SqSIF8vef2tNvyW9Pk9tx1ggJmpOlwLlwuJWmeM1Lqea1Vvt8T070mtQX1RiO8/0CNSZ3f8QSJ2pCvrSYVXc3+QjTUsqeyrsfD8q0cS5y91YysUfunGKcPCsLBzEBhLY7zIDqupcaBhuQON8YGf1tGxkM4BrYJ5q6/w/HFd0mSTu/xHWiDCD5Lm+WVLg5rPs+UAi7EXKpCcuJiWYMMRfVths9NNg1QQKoYuJ9JLevxE8A+Y/l8EDCwEtcPr5PLWaSV4HnRctsv41jKKeZTar3wG1hzmuDJB8SeMPmIuYsEp4wWavcS4iUu2t1gQf1Ln391rtQneYoBp0ywPSPJQX7M4RwOtbUWShVCAccAope8NfdOrMhcBhr83OkhkqPWpnrtsY15Z3I27bFpQeFRfF4hwp/HOZyeb25NMxuPvwLAThhDx4RHNOHcY+s5aME1/h11w=

after_script:
  - ./fixup.sh
